[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "My_project"
version = "0.1.0"
description = "Example project"
requires-python = ">=3.8"
dependencies = [
    "colorama==0.4.6",
    "ruff==0.14.4",
]